### ISSUE TITLE
Cannot run template.yml in Ubuntu16 (PyCharm 2019)

### ISSUE THREAD

**Issue by 179416326** [Orange-OpenSource/synthetic-tm-generator#1]
Hi, when i ran this demo with cmd(Ubuntu16 (PyCharm 2019), without docker):
python generate.py --max-node-class 1 template.yml output_file.yml 0 1
 
i got this error:
generate.py:666: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  template = yaml.load(fh)
Traceback (most recent call last):
  File "generate.py", line 680, in <module>
    generate_link_loads(data, nodes, args.mipgap, args.total_traffic, args.mean_link_load, args.method_flow_assign)
  File "generate.py", line 526, in generate_link_loads
    objective = methods[flow_assign_method](data, tm, mipgap)
  File "generate.py", line 357, in assign_flow_rates_heuristic
    od_pairs = sorted(od_pairs, cmp=make_comparator(od_pair_infos), reverse=True)
TypeError: 'cmp' is an invalid keyword argument for this function

i have apt install python-tk and glpk-utils. Please have a look at it. Thanks. 

Wayne.

**Comment by 179416326** [comment]
My python is 3.6.7.

**Comment by pchaigno** [comment]
Did you try running with Python 2.7?

**Comment by 179416326** [comment]
Thanks for your replying in time. I fixed it in Python 3.6 in this way:
od_pairs = sorted(od_pairs, key = cmp_to_key(make_comparator(od_pair_infos)), reverse=True)
And it works well.

**Comment by 179416326** [comment]
There is another question: how can I get the legit load matrix in flow ratio between each node? I saw the output_file.yml using "example_template.yml" with command "python generate.py --max-node-class 1 template.yml output_file.yml 0 1 --display-network", it turned out to be like this:
[[0, 37446.0, 82774.0, 54045.0, 24338.0]
 [34630.0, 0, 29036.0, 0, 0]
 [62063.0, 25190.0, 0, 51826.0, 0]
 [45159.0, 0, 39829.0, 0, 0]
 [17550.0, 0, 0, 0, 0]]

**Comment by pchaigno** [comment]
> Thanks for your replying in time. I fixed it in Python 3.6 in this way:
> od_pairs = sorted(od_pairs, key = cmp_to_key(make_comparator(od_pair_infos)), reverse=True)
> And it works well.

Could you send a PR for that?

> There is another question: how can I get the legit load matrix in flow ratio between each node? I saw the output_file.yml using "example_template.yml" with command "python generate.py --max-node-class 1 template.yml output_file.yml 0 1 --display-network", it turned out to be like this:
> [[0, 37446.0, 82774.0, 54045.0, 24338.0]
> [34630.0, 0, 29036.0, 0, 0]
> [62063.0, 25190.0, 0, 51826.0, 0]
> [45159.0, 0, 39829.0, 0, 0]
> [17550.0, 0, 0, 0, 0]]

I'm not sure what you're asking. `example_template.yml` is a really small example so the small traffic matrix is expected. `template_free.yml` is a bit better if you want something bigger.

**Comment by 179416326** [comment]
Sorry for what PR means? You mean Pull Request?

**Comment by pchaigno** [comment]
Yes.

**Comment by 179416326** [comment]
Pull requested. For my question, I try to control traffic intensity levels (TI) of a network for example: 5 links, each link with capacity of 10Mbps. I want the traffic intensity level of 25%. How should I configure the command?

**Comment by pchaigno** [comment]
> Pull requested.

Thanks!

> For my question, I try to control traffic intensity levels (TI) of a network for example: 5 links, each link with capacity of 10Mbps. I want the traffic intensity level of 25%. How should I configure the command?

You can configure the average load on links with `--mean-link-load 0.25`.
